"""Real Agent execution boundary for the Environment Foundry.

The package exports one real Codex SDK backend and the immutable contracts used
by Controller/Designer/Builder.  It intentionally exports no mock, manual,
template, replay, or generic process backend.
"""

from .authority import (
    AgentAuthorityViolation,
    AgentOutputAuthority,
    EpisodeActionProposalOutput,
    SemanticAdvisoryOutput,
    WorkspaceProposalOutput,
    assert_agent_output_advisory,
    register_agent_output_contract,
    registered_agent_output_contracts,
)
from .capabilities import (
    CapabilityResolutionError,
    EffectiveCapabilityPlan,
    ExternalCapabilitySet,
    NodeCapabilityRequirement,
    RoleCapabilityMaximum,
    compile_effective_capability_plan,
)
from .codex_sdk import CodexSdkBackend
from .contracts import (
    CredentialDescriptor,
    InvocationBackend,
    InvocationError,
    InvocationEvent,
    InvocationLimits,
    InvocationRequest,
    InvocationResult,
    InvocationSession,
    InvocationStatus,
    InvocationUsage,
    ReasoningEffort,
    ResolvedAgentProfile,
    ResolvedBundle,
    SandboxMode,
    TokenBreakdown,
)
from .profiles import (
    AgentProfileSpec,
    CodexLoginBinding,
    CredentialBinding,
    CredentialResolutionError,
    HookBundleSpec,
    McpServerSpec,
    McpTransport,
    ProfileResolutionError,
    ProfileResolver,
    SkillBundleSpec,
    verify_resolved_profile,
)

__all__ = [
    "AgentAuthorityViolation",
    "AgentOutputAuthority",
    "AgentProfileSpec",
    "CapabilityResolutionError",
    "CodexLoginBinding",
    "CodexSdkBackend",
    "CredentialBinding",
    "CredentialDescriptor",
    "CredentialResolutionError",
    "EffectiveCapabilityPlan",
    "ExternalCapabilitySet",
    "EpisodeActionProposalOutput",
    "HookBundleSpec",
    "InvocationBackend",
    "InvocationError",
    "InvocationEvent",
    "InvocationLimits",
    "InvocationRequest",
    "InvocationResult",
    "InvocationSession",
    "InvocationStatus",
    "InvocationUsage",
    "McpServerSpec",
    "McpTransport",
    "NodeCapabilityRequirement",
    "ProfileResolutionError",
    "ProfileResolver",
    "ReasoningEffort",
    "ResolvedAgentProfile",
    "ResolvedBundle",
    "RoleCapabilityMaximum",
    "SandboxMode",
    "SemanticAdvisoryOutput",
    "SkillBundleSpec",
    "TokenBreakdown",
    "WorkspaceProposalOutput",
    "assert_agent_output_advisory",
    "register_agent_output_contract",
    "registered_agent_output_contracts",
    "compile_effective_capability_plan",
    "verify_resolved_profile",
]
