"""Real Agent execution boundary for the Environment Foundry.

The package exports explicit Codex-agentic and direct-structured adapters,
selected only through one ``InvocationBackend`` router. It intentionally
exports no mock, manual, template, replay, or generic process backend.
"""

from .authority import (
    AgentAuthorityViolation,
    AgentOutputAuthority,
    EpisodeActionProposalOutput,
    SemanticAdvisoryOutput,
    WorkspaceProposalOutput,
    assert_agent_output_advisory,
    register_agent_output_contract,
    registered_agent_output_contracts,
)
from .capabilities import (
    CapabilityResolutionError,
    EffectiveCapabilityPlan,
    ExternalCapabilitySet,
    NodeCapabilityRequirement,
    RoleCapabilityMaximum,
    compile_effective_capability_plan,
)
from .codex_sdk import CodexSdkBackend
from .contracts import (
    CredentialDescriptor,
    InvocationBackend,
    InvocationError,
    InvocationEvent,
    InvocationExecutionMode,
    InvocationLifecyclePhase,
    InvocationLifecycleSink,
    InvocationLifecycleSupervision,
    InvocationLimits,
    InvocationOwnerKind,
    InvocationOwnership,
    InvocationRequest,
    InvocationResult,
    InvocationSession,
    InvocationStatus,
    InvocationUsage,
    ReasoningEffort,
    ResolvedAgentProfile,
    ResolvedBundle,
    SandboxMode,
    TokenBreakdown,
)
from .control_plane import InvocationControlPlane
from .control_store import (
    InvocationAlreadyActiveError,
    InvocationControlRecord,
    InvocationControlStore,
    InvocationControlStoreError,
    InvocationPhysicalStatus,
    InvocationRequestShape,
    InvocationTerminalFact,
)
from .direct_llm import DirectLlmBackend
from .ownership import standalone_component_ownership
from .profiles import (
    AgentProfileSpec,
    CodexLoginBinding,
    CredentialBinding,
    CredentialResolutionError,
    McpServerSpec,
    McpTransport,
    ProfileResolutionError,
    ProfileResolver,
    SkillBundleSpec,
    safe_profile_resolution_category,
    verify_resolved_profile,
)
from .recovery import (
    AttributionSupport,
    InvocationAttributionLens,
    InvocationControlRouteLivenessChecker,
    InvocationFailureClass,
    InvocationRecoveryDecision,
    InvocationRecoveryEvidence,
    InvocationRecoveryPolicy,
    InvocationRecoveryRoute,
    LensAssessment,
    RouteLivenessCheck,
    RouteLivenessChecker,
)
from .routing import RoutedInvocationBackend

__all__ = [
    "AgentAuthorityViolation",
    "AgentOutputAuthority",
    "AgentProfileSpec",
    "CapabilityResolutionError",
    "CodexLoginBinding",
    "CodexSdkBackend",
    "CredentialBinding",
    "CredentialDescriptor",
    "CredentialResolutionError",
    "DirectLlmBackend",
    "EffectiveCapabilityPlan",
    "ExternalCapabilitySet",
    "EpisodeActionProposalOutput",
    "InvocationAlreadyActiveError",
    "InvocationBackend",
    "InvocationControlPlane",
    "InvocationControlRecord",
    "InvocationControlStore",
    "InvocationControlStoreError",
    "InvocationError",
    "InvocationExecutionMode",
    "InvocationEvent",
    "InvocationLifecyclePhase",
    "InvocationLifecycleSink",
    "InvocationLifecycleSupervision",
    "InvocationLimits",
    "InvocationOwnerKind",
    "InvocationOwnership",
    "InvocationPhysicalStatus",
    "InvocationRequestShape",
    "InvocationRequest",
    "InvocationResult",
    "InvocationAttributionLens",
    "InvocationFailureClass",
    "InvocationRecoveryDecision",
    "InvocationRecoveryEvidence",
    "InvocationRecoveryPolicy",
    "InvocationRecoveryRoute",
    "InvocationControlRouteLivenessChecker",
    "InvocationSession",
    "InvocationStatus",
    "InvocationTerminalFact",
    "InvocationUsage",
    "AttributionSupport",
    "LensAssessment",
    "McpServerSpec",
    "McpTransport",
    "NodeCapabilityRequirement",
    "ProfileResolutionError",
    "ProfileResolver",
    "safe_profile_resolution_category",
    "ReasoningEffort",
    "ResolvedAgentProfile",
    "ResolvedBundle",
    "RoleCapabilityMaximum",
    "RouteLivenessCheck",
    "RouteLivenessChecker",
    "RoutedInvocationBackend",
    "SandboxMode",
    "SemanticAdvisoryOutput",
    "SkillBundleSpec",
    "standalone_component_ownership",
    "TokenBreakdown",
    "WorkspaceProposalOutput",
    "assert_agent_output_advisory",
    "register_agent_output_contract",
    "registered_agent_output_contracts",
    "compile_effective_capability_plan",
    "verify_resolved_profile",
]
